# -*- coding: utf-8 -*-
"""Task_management _app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdCO8iyBuqVX70-gKzUU67et6BjSOVD2
"""

def Tasks():
  Tasks = []
  print(" Welcome to the Task Management App")

  total_task = int(input("Enter how many times you want to add = "))

  for i in range(1, total_task + 1):
    task_name = input(f"Enter task{i} = ")
    Tasks.append(task_name)

  print(f"Today's tasks are\n {Tasks}")

  #  Add, Update, Delete, View, Exit/Stop
  while True:
    operation = int(input("Enter 1 - Add\n2 - Update\n3 - Delete\n4 - View\n5 - Exit/Stop\n"))

    if operation == 1:
      add = input("Enter the task you want to add = ")
      Tasks.append(add)
      print(f"Task {add} has been successfully added...")

    #  Update the Task
    elif operation == 2 :
      updated_val = input("Enter the Task you want to update = ")
      if updated_val in Tasks:
        up = input("Enter New Task = ")
        ind = Tasks.index(updated_val)  # uses index method to check index position
        Tasks[ind] = up
        print(f" Updated Task {up} ")
      else:
        print("Task not found")

    # Delete the Task
    elif operation == 3:
      del_val = input("Enter the Task you want to delete = ")
      if del_val in Tasks:
        Tasks.remove(del_val)
        print(f"Task {del_val} has been successfully deleted...")
      else:
        print("Task not found")

    # view the Tasks
    elif operation == 4:
      print(f"Total Tasks = {Tasks}")

    # To exit/ stop
    elif operation == 5:
      print("Thanks for using the app...")
      break                   # loop will end here

    else:
      print("Invalid Input")

Tasks()

